isYud7AsdGmMHVQd_bw0m3LrMD9NcYge8IMZZheac8UTncky1n0KgEb6n2jajdNfqGXPLGHn3IeRDA

SELECT match_participant_champion.champion_api_name, match_participant_champion_item.item_id FROM match_participant_champion LEFT JOIN match_participant_champion_item ON match_participant_champion.match_id = match_participant_champion_item.match_id AND match_participant_champion.puuid = match_participant_champion_item.puuid AND match_participant_champion.champion_api_name = match_participant_champion_item.champion_api_name
